version: '3'

services: 
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: schoolAdmin
      MYSQL_DATABASE: schoolDb
      MYSQL_USER: school
      MYSQL_PASSWORD: school
    networks:
      - wpsite
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    # restart: unless-stopped
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: schoolAdmin 
    networks:
      - wpsite
  # Spring-Boot-school 
  rest_api_boot:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8082'
    restart: on-failure
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=school
      - DATABASE_PASSWORD=school
      - DATABASE_NAME=schoolDb
      - DATABASE_PORT=3306
     #WAIT_HOSTS: db:3306
    networks: 
      - wpsite
      
networks:
  wpsite:
volumes:
  db_data: